{
  "hash": "7aa06b2b910930e704126e9f36d4c888",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Intro to Bayesian Thinking\"\nsubtitle: \"Day 1\"\nformat: \n  revealjs:\n    auto-stretch: true\n    slide-number: true\n    incremental: true\n    theme: [\"../../templates/slides-style.scss\"]\n    logo: https://www.stat.uci.edu/bayes-bats/img/logo.png\n    title-slide-attributes: \n      data-background-image: https://www.stat.uci.edu/bayes-bats/img/logo.png\n      data-background-size: 12%\n      data-background-position: 50% 95%\n---\n\n\n\n# {.center}\n\nNote that this lecture is based on [Chapters 1-2 of Bayes Rules! book](https://www.bayesrulesbook.com/chapter-1.html).\n\n\n# Introduction to Bayesian Statistics\n\n\n## Bayesian Knowledge Building\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](img/bayes_diagram.png){fig-align='center'}\n:::\n:::\n\n\n\n## Frequentist Knowledge Building\n\n![](img/data.png){width=2in,fig-align=\"center\"}\n\n## Balancing Act of Bayesian Analysis \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](img/bayes-balance-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Interpretation of Probability \n\n**Bayesian**: a probability measures the relative plausibility of an event.\n\n**Frequentist**: a probability measures the long-run relative frequency of a repeatable event. In fact, “frequentists” are so named because of their interpretation of probability as a long-run relative frequency.\n\n\n\n## Same Data, Different Priors\n\n(1) Kaya claims that they can predict the outcome of a coin flip. To test their claim, you flip a fair coin 10 times and they correctly predict all 10! \n\n(2) Fan claims that they can distinguish natural and artificial sweeteners. To test their claim, you give them 10 sweetener samples and they correctly identify each! In light of these experiments, what do you conclude?\n\n-   [You’re more confident in Fan’s claim than Kaya’s claim.]{.dukeblue-text}\n\n-   [The evidence supporting Kaya’s claim is just as strong as the evidence supporting Fan’s claim.]{.dukeblue-text}\n\n\n\n\n\n## Hypothesis Testing\n\n\n::: {.callout-warning icon=false}\n## Discussion question\n\nSuppose that during a recent doctor’s visit, you tested positive for a very rare disease. If you only get to ask the doctor one question, which would it be?\n\n:::\n\n\na. What’s the chance that I actually have the disease?  \nb. If in fact I don’t have the disease, what’s the chance that I would’ve gotten this positive test result?\n\n. . .\n\n$P(\\text{disease} | +)$ is a mathematical expression of question (a), and $P(+ | \\text{disease}^c)$ expresses (b). Frequentist analysis gives us an estimate of (b), and Bayes can help us get to (a).\n\n\n\n## Notes on Bayesian History\n\n- Named after Thomas Bayes (1701-1761)\n\n\n- Frequentist statistics is more popular; Bayesian statistics is surging in popularity \n\n\n- Computing, computing, computing\n\n\n- It is harder to adopt newer methods. Change is happening slowly. \n\n\n- We can embrace subjectivity. \n\n\n\n## Optional\n\nWatch [How Data Nerds Found A 131-Year-Old Sunken Treasure](https://fivethirtyeight.com/features/how-data-nerds-found-a-131-year-old-sunken-treasure/)\n\n\n\n# Review of Probability\n\n## How Good is a Mammogram?\n\n|         | Cancer | No Cancer | Total[^1] |\n|---------|-------:|----------:|----------:|\n| Mammo + | 85     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     9900  |   10000    |\n\nLet $A$ represent the event a mammogram is positive for breast cancer (Mammo +), and let $B$ represent the event that a woman has cancer.\n\n\n\n[^1]: Data based on breast cancer prevalence at age 40 for women and standard screening mammogram sensitivity and specificity\n\n## How Good is a Mammogram?\n\n|         | Cancer | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | 85     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     9900  |   10000    |\n\n$$P(\\text{Cancer})= ~?$$\n$$P(\\text{Cancer and Mammo +})= ~?$$\n$$P(\\text{Cancer given Mammo +})= ~?$$\n\n. . .\n\nCalculate these probabilities and express them using the notation for events $A$ and $B$.\n\n## Marginal Probability\n\n|         | Cancer | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | 85     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | **100**    |     9900  |   **10000**    |\n\n$P(\\text{Cancer})= ~?$\n\n. . . \n\n$P(B) = \\frac{100}{10000}= 0.01$\n\n. . . \n\n$P(B^C)$ is called **complement** of event $B$ and represents the probability of selecting someone who does not have cancer.  \n\n. . . \n\n$P(B)$ represents a **marginal probability**. So do $P(B^C)=1-P(B)$, $P(A)$, and $P(A^C)$. We can calculate these quantities using only the values in the margins of the contingency table.\n\n## Conditional Probability\n\n|         | Cancer | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | **85**     |    990    |   **1075**   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     9900  |   10000    |\n\n\n$P(\\text{Cancer given Mammo +})= ~?$\n\n. . . \n\n$P(B \\mid A) = \\frac{85}{1075}= 0.079$\n\n. . .\n\n$P(B \\mid A)$ is a **conditional probability**.  So are $P(B^C \\mid A)=1-P(B \\mid A)$, $P(B \\mid A^C)$, $P(B^c \\mid A^C)$, $P(A \\mid B)$, etc. To calculate these probabilities, we focus on the row or column of the given information, *reducing* our sample space to that only of the given information. Note that $P(B \\mid A) \\neq P(A \\mid B)$ - order matters.\n\n## Joint Probability\n\n|         | Cancer | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | **85**     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     9900  |   **10000**    |\n\n$P(\\text{Cancer and Mammo +})= ~?$\n\n. . . \n\n$P(B \\cap A) = \\frac{85}{10000}= 0.0085$\n\n. . . \n\n$P(B \\cap A)$ represents a **joint probability**. So do $P(B^C \\cap A)$, $P(B \\cap A^C)$, etc. \n\n. . . \n\nNote that $P(A \\cap B)=P(B \\cap A)$. Order does not matter here.\n\n# Bayes' Rule for Events\n\n## Breast Cancer Screening\n\n|         | Cancer | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | 85     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     9900  |   10000    |\n\nSuppose a 40 year old woman, Maya, goes to a clinic for a screening mammogram.  The **prevalence** of breast cancer among women in this age group is 1%. We can think of this as **prior** information about whether Maya has breast cancer.\n\n## Breast Cancer Screening\n\nMaya has the screening mammogram and receives a positive finding.  Taking this new data into account, which of the following describes your **posterior** understanding of the probability that Maya has breast cancer?\n\na. These tests yield false positives all the time.  Let's see what happens at the next screening mammogram in a couple years.\nb. The chances Maya has cancer have risen, but it is still much more likely that she is cancer-free than that she has cancer. Still, she should follow the recommendation of the doctor for follow-up diagnostic testing so that she doesn't miss the opportunity for early treatment just in case.\nc. The chances Maya has cancer are very high. She should have follow-up testing as soon as possible and start thinking about treatment.\n\n## The Prior Model\n\n| Quantity | $B$ | $B^C$ | Sum |\n|:-----|------:|------:|-----:|\n| prior probability | 0.01 | 0.99 | 1 |\n\n## Likelihood\n\nLet's go back at the table and calculate the probability of a positive mammogram result (event $A$) in two cases: when a woman has cancer (event $B$), and when a woman does not have cancer (event $B^C$).\n\n## Likelihood Mammo + When Cancer is Present\n\n|         | **Cancer** | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | **85**     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | **100**    |     9900  |   10000    |\n\nWhen a woman has cancer, we expect the screening mammogram to be positive with probability $P(A \\mid B)=\\frac{85}{100}=0.85$. This quantity is also called the **sensitivity** of the mammogram. We like our tests to have high sensitivity, picking up most of the cancers that are present.  \n\n\n\n\n## Likelihood Mammo + When Cancer is Not Present\n\n|         | Cancer | **No Cancer** | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | 85     |    **990**    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     **9900**  |   10000    |\n\nWhen a woman has no cancer, we expect the screening mammogram to be positive with probability $P(A \\mid B^C)=\\frac{990}{9900}=0.10$. A related quantity, $1-P(A \\mid B^C)=P(A^C \\mid B^C)=0.90$, is called the **specificity** of the mammogram.  We also want specificity to be high, so that women without cancer are told they are cancer-free and do not need to go through additional follow up.\n\n## Likelihoods\n\nWe can call these quantities **likelihoods**, as they compare the likelihood of a positive mammogram under the two scenarios. Notation can be confusing, as $L(\\cdot \\mid A)=P(A \\mid \\cdot)$.\n\n$L(B \\mid A)=P(A \\mid B) = 0.85$ (our data of a positive mammogram are highly compatible with cancer)\n\n$L(B^C \\mid A)=P(A \\mid B^C)=0.10$ (data of a positive mammogram are less compatible with no cancer)\n\nWhen a woman has breast cancer, we are much more likely to get the data of a positive mammogram than we are when a woman is cancer-free. Still, cancer is not common.\n\n. . . \n\nWe can use the **likelihood function** to weigh the likelihoods of our data, a positive mammogram, under different cancer diagnosis scenarios. We can use it to \nupdate our probability that a person has cancer.\n\n## Likelihood \n\n| Quantity | $B$ | $B^C$ | Sum |\n|:-----|------:|------:|-----:|\n| prior probability | 0.01 | 0.99 | 1 |\n| likelihood | 0.85 | 0.10 | 0.95 |\n\nNote the likelihood function is not a probability function, as it does not follow the **law of total probability** given by $P(B)+P(B^C)=1$. It provides a framework to evaluate the relative compatibility of our data (here, the positive mammogram) with the events $B$ and $B^C$.\n\n. . . \n\nWhile the prior data suggests it is unlikely a 40 year old woman has breast cancer, the data provide evidence in favor of cancer diagnosis because $L(B \\mid A) > L(B^C \\mid A)$. We can use Bayes' rule to help us determine how likely a cancer diagnosis is given this evidence.\n\n## Bayes' Rule\n\n**Bayes' rule** gives us a formal way to update our beliefs based on new infomration.  It says $P(B \\mid A) = \\frac{P(A \\cap B)}{P(A)}= \\frac{P(A \\mid B)P(B)}{P(A)}.$ Using our likelihoods, we can express this as $$P(B \\mid A) = \\frac{P(B)L(B \\mid A)}{P(A)}.$$\n\nMaya would like to know her chances of having cancer. Several papers have shown that even doctors strongly overestimate her chances of having cancer given the positive mammogram finding.\n\nRecall **Law of Total Probability**:  $P(A)=P(A \\cap B) + P(A \\cap B^C)$ or, equivalently, $P(A)=P(A \\mid B)P(B)+P(A \\mid B^C)P(B^C)$.\n\n## Calculations\n\n:::: {.columns}\n\n::: {.column width=\"70%\"}\n|         | Cancer | No Cancer | Total |\n|---------|-------:|----------:|----------:|\n| Mammo + | 85     |    990    |   1075   |\n| Mammo - | 15     |   8910    |  8925   |\n| Total   | 100    |     9900  |   10000    |\n:::\n\n::: {.column width=\"30%\"}\n\n$P(B) = \\frac{100}{10000} = 0.01$\n\n$P(A \\mid B) = \\frac{85}{100} = 0.85$ \n\n$P(A \\mid B^C) = \\frac{990}{9900} = 0.10$\n\n\n:::\n\n::::\n\n$$P(B \\mid A) = \\frac{P(B)L(B \\mid A)}{P(A \\mid B)P(B)+P(A \\mid B^C)P(B^C)}$$\n\n. . . \n\n$$P(B \\mid A) = \\frac{0.01 \\times 0.85 }{0.85 \\times 0.01 + 0.10 \\times 0.99}=0.079$$\n\n## The Posterior Model\n\n\n| Quantity | $B$ | $B^C$ | Sum |\n|:-----|------:|------:|-----:|\n| prior probability | 0.01 | 0.99 | 1 |\n| likelihood | 0.85 | 0.10 | 0.95 |\n| posterior probability | 0.079 | 0.921 | 1 |\n\n## Summary {.increased-line}\n\n$$P(B \\mid A) = \\frac{P(B)L(B \\mid A)}{P(A)}$$\n\n$$ \\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{\\text{marginal probability}}$$\n\n$$ \\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{\\text{normalizing constant}}$$\n\n\n\n\n# Bayes' Rule for Random Variables\n\n\n\n\n\n\n## Notation\n\n- We will use *Greek letters* (eg: $\\pi, \\beta, \\mu$) to denote our primary variables of interest.\n\n- We will use *capital Roman letters* toward the end of the alphabet (eg: $X, Y, Z$) to denote random variables related to our data.  \n\n- We denote an observed *outcome* of $Y$ (a constant) using lower case $y$.  \n\n\n\n## Review: Discrete Probability Models \n\nLet $Y$ be a discrete random variable with probability mass function (pmf) $f(y)$.  Then the pmf defines the probability of any given $y$, $f(y) = P(Y = y)$, and has the following properties:    \n\n- $\\sum_{\\text{all } y} f(y) = 1$  \n\n- $0 \\le f(y) \\le 1$ for all values of $y$ in the range of $Y$\n\n\n\n\n## PhD Admissions\n\n(Example from [bayesrulesbook.com](https://bayesrulesbook.com))\n\nLet $Y$ be a random variable that represents the number of applicants admitted to a PhD program that has received applications from 5 prospective students. That is, $\\Omega_Y = \\{0, 1, 2, 3, 4, 5\\}$. We are interested in the parameter $\\pi$, which represents the probability of acceptance to this program. For demonstrative purposes, we will only consider three possible values of $\\pi$: 0.2, 0.4, and 0.8. \n\n\n\n\n\n## Prior Model for $\\pi$\n\nYou are now a true Bayesian and decide to consult with an expert who knows the specific PhD program well, and the following is the prior distribution the expert suggests you use in your analysis. \n\n| $\\pi$ | 0.2 | 0.4 | 0.8|\n|:---:|---:|---:|---:|\n| $f(\\pi)$ | 0.7 | 0.2 | 0.1 |\n\nThe expert thinks that this is quite a hard-to-get-into program.\n\n\n\n## From Prior to Posterior {.increased-line}\n\n-   We have a prior model for $\\pi$ that is $f(\\pi)$. \n\n-   In light of observed data $y$, we can update our ideas about $\\pi$. \n\n-   We will call this the posterior model $f(\\pi|y)$.  \n\n-   For this update, we will need data, which we have not yet observed. \n\n\n## Consider Data\n\nFor the two scenarios below fill out the table (twice). For now, it is OK to use your intuition to guesstimate. \n\n\n| | $\\pi$ | 0.2 | 0.4 | 0.8|\n|:---|:---:|---:|---:|---:|\n| | $f(\\pi)$ | 0.7 | 0.2 | 0.1 |\n| Scenario 1 | $f(\\pi \\mid y)$ | | | |\n| Scenario 2 | $f(\\pi \\mid y)$ | | | |\n\n\nScenario 1: What if this program accepted five of the five applicants?\n\nScenario 2: What if this program accepted none of the five applicants? \n\n\n\n\n## Intuition vs. Reality\n\nYour intuition may not be Bayesian if\n\n-     you have only relied on the prior model to decide on the posterior model\n\n-     you have only relied on the data to decide on the posterior model\n\n\n::: {.callout-warning icon=false}\n## Discussion question\n\n-   What would the probabilities in each row be like if we only relied on the prior model?  If we only relied on the data?\n\n:::\n\n-   Bayesian statistics is a balancing act and we will take both the prior and the data to get to the posterior. Don't worry if your intuition was wrong. As we practice more, you will learn to think like a Bayesian.\n\n\n\n## Likelihood\n\nWe do not know $\\pi$, but for now let's consider one of the three possibilities: $\\pi = 0.2$. If $\\pi$ were 0.2, what is the probability that we would observe 4 of the 5 applicants get admitted to the program? Would you expect this probability to be high or low?\n\n. . . \n\nCan you calculate an exact value?\n\n\n## The Binomial Model\n\nLet random variable $Y$ be the *number of successes* (eg: number of accepted applicants) in $n$ *trials* (eg: applications).  Assume that the number of trials is *fixed*, the trials are *independent*, and the *probability of success* (eg: probability of acceptance) in each trial is $\\pi$.  Then the *dependence* of $Y$ on $\\pi$ can be modeled by the Binomial model with **parameters** $n$ and $\\pi$.  In mathematical notation:\n \n$$Y | \\pi \\sim \\text{Bin}(n,\\pi) $$\n\nthen, the Binomial model is specified by a conditional pmf:    \n\n$$f(y|\\pi) = {n \\choose y} \\pi^y (1-\\pi)^{n-y} \\;\\; \\text{ for } y \\in \\{0,1,2,\\ldots,n\\}$$\n\n\n\n## The Binomial Model\n\n$f(y = 4 | \\pi = 0.2) = {5 \\choose 4} 0.2^40.8^1 = \\frac{5!}{(5-4)! 4!} 0.2^40.8^1= 0.0064$  \n\nor, using R,\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 4, size = 5, prob = 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0064\n```\n\n\n:::\n:::\n\n\n\n\n## The Binomial Model \n\nIf $\\pi$ were 0.2, what is the probability that we would observe 3 of the 5 applicants get admitted to the program? Would you expect this probability to be high or low?\n\n$f(x = 3 | \\pi = 0.2) = {5 \\choose 3} 0.2^30.8^2 = \\frac{5!}{(5-3)! 3!} 0.2^30.8^2 =0.0512$  \n\nor using R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 3, size = 5, prob = 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0512\n```\n\n\n:::\n:::\n\n\n\n\n\n## The Binomial Model\n\nRather than doing this one-by-one we can let R consider all different possible observations of y, 0 through 5. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 0:5, size = 5, prob = 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.32768 0.40960 0.20480 0.05120 0.00640 0.00032\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Probabilities for $y_i$'s if $\\pi = 0.2$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](1-lec-intro-bayes-thinking_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n\n## Other Possibilities for $\\pi$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](1-lec-intro-bayes-thinking_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n## Data\n\nThe admissions committee has announced that they have accepted 3 of the 5 applicants. \n\n\n\n## Data\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](1-lec-intro-bayes-thinking_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n## Likelihood\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](1-lec-intro-bayes-thinking_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n## Likelihood\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 3, size = 5, prob = 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0512\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 3, size = 5, prob = 0.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2304\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 3, size = 5, prob = 0.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2048\n```\n\n\n:::\n:::\n\n\n\n\n\n## Likelihood\n\n| $\\pi$ | 0.2 | 0.4 | 0.8|\n|:---:|---:|---:|---:|\n| $L(\\pi \\mid y=3)$ | 0.0512 | 0.2304 | 0.2048 |\n\n\n\n## Likelihood\n\nThe likelihood function $L(\\pi|y=3)$ is the same as the conditional probability mass function $f(y|\\pi)$ at the observed value $y = 3$.\n\n## Likelihood vs pmf\n\nWhen $\\pi$ is known, the **conditional pmf** $f(\\cdot | \\pi)$ allows us to compare the probabilities of different possible values of data $Y$ (eg: $y_1$ or $y_2$) occurring with $\\pi$: \n\n$$f(y_1|\\pi) \\; \\text{ vs } \\; f(y_2|\\pi) \\; .$$  \n\nWhen $Y=y$ is known, the **likelihood function** $L(\\cdot | y) = f(y | \\cdot)$ allows us to compare the relative likelihoods of different possible values of $\\pi$ (eg: $\\pi_1$ or $\\pi_2$) given that we observed data $y$:\n\n$$L(\\pi_1|y) \\; \\text{ vs } \\; L(\\pi_2|y) \\; .$$\n\n\n\n\n\n## Getting Closer to Conclusion {.increased-line}\n\nThe expert assigned the highest weight to $\\pi = 0.2$. \n\nHowever the data $y = 3$ suggests that $\\pi = 0.4$ is more likely. \n\nWe will continue to consider all the possible values of $\\pi$.\n\nNow is a good time to balance the prior and the likelihood.\n\n\n## From Events to Random Variables {.increased-line}\n\n$\\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{\\text{marginal probability of data}}$\n\n. . . \n\n$\\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{f(y = 3)}$\n\n. . . \n\n$\\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{f(y = 3 \\cap \\pi = 0.2) + f(y = 3 \\cap \\pi = 0.4) + f(y = 3 \\cap \\pi = 0.8)}$\n\n. . . \n\n$\\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{f(y = 3 | \\pi = 0.2) \\cdot f(\\pi = 0.2) + f(y = 3 | \\pi = 0.4) \\cdot f(\\pi = 0.4) + f(y = 3 | \\pi = 0.8) \\cdot f(\\pi = 0.8)}$\n\n\n\n## Normalizing Constant {.increased-line}\n\n\n$\\text{posterior} = \\frac{\\text{prior} \\times \\text{likelihood}}{f(y = 3 | \\pi = 0.2) \\cdot f(\\pi = 0.2) + f(y = 3 | \\pi = 0.4) \\cdot f(\\pi = 0.4) + f(y = 3 | \\pi = 0.8) \\cdot f(\\pi = 0.8)}$\n\n\nThus $f(y = 3) =$\n\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\ndbinom(x = 3, size = 5, prob = 0.2) * 0.7 +\ndbinom(x = 3, size = 5, prob = 0.4) * 0.2 +\ndbinom(x = 3, size = 5, prob = 0.8) * 0.1\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1024\n```\n\n\n:::\n:::\n\n\n\n\n## Posterior \n\n\n| $\\pi$ | 0.2 | 0.4 | 0.8|\n|:---:|---:|---:|---:|\n| $f(\\pi)$ | 0.7 | 0.2 | 0.1 |\n| $L(\\pi \\mid y=3)$ | 0.0512 | 0.2304 | 0.2048 |\n| $f(\\pi \\mid y=3)$ | 0.35 | 0.45 | | \n\n. . . \n\n$f(\\pi=0.8 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n. . . \n\n$= \\frac{0.1 \\times 0.2048}{0.1024}$\n\n. . . \n\n$= 0.2$\n\n. . . \n\n## Posterior \n\n| $\\pi$ | 0.2 | 0.4 | 0.8|\n|:---:|---:|---:|---:|\n| $f(\\pi)$ | 0.7 | 0.2 | 0.1 |\n| $L(\\pi \\mid y=3)$ | 0.0512 | 0.2304 | 0.2048 |\n| $f(\\pi \\mid y=3)$ | 0.35 | 0.45 | 0.20 | \n\n\n\n## Why is Normalizing Constant a \"Normalizing Constant\"?\n\n::: {.panel-tabset}\n\n## $\\pi=0.2$\n\n$f(\\pi=0.2 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n$= \\frac{0.7 \\times 0.0512}{0.1024}$\n\n\n## $\\pi=0.4$\n\n$f(\\pi=0.4 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n$= \\frac{0.2 \\times 0.2304}{0.1024}$\n\n## $\\pi=0.8$\n\n$f(\\pi=0.8 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n$= \\frac{0.1 \\times 0.2048}{0.1024}$\n\n:::\n\n\n\n\n\n## Why is Normalizing Constant a \"Normalizing Constant\"?\n\nHere, our normalizing constant is 0.1024.\n\n::: {.panel-tabset}\n\n## $\\pi=0.2$\n\n$f(\\pi=0.2 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n$= \\frac{0.7 \\times 0.0512}{0.1024}$\n\n$\\propto {0.7 \\times 0.0512}$\n\n\n## $\\pi=0.4$\n\n$f(\\pi=0.4 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n$= \\frac{0.2 \\times 0.2304}{0.1024}$\n\n$\\propto {0.2 \\times 0.2304}$\n\n## $\\pi=0.8$\n\n$f(\\pi=0.8 | y = 3) = \\frac{f(\\pi)L(\\pi|y =3)}{f(y = 3)}$\n\n$= \\frac{0.1 \\times 0.2048}{0.1024}$\n\n$\\propto {0.1 \\times 0.2048}$\n\n:::\n\nWithout the normalizing constant, the sum of these probabilities is $0.7 \\times 0.0512 + 0.2 \\times 0.2304 +  0.1 \\times 0.2048 = 0.1024$. With division by the normalizing constant the resulting probabilities sum to 1, as needed for a probability distribution.\n\n\n## Why is Normalizing Constant a \"Normalizing Constant\"?\n\n\n$$f(\\pi|y) \\propto f(\\pi)L(\\pi|y)$$\n\n\n\n## In Summary\n\nEvery Bayesian analysis consists of three common steps.   \n\n1.Construct a **prior model** for your variable of interest, $\\pi$.    \n    A prior model specifies two important pieces of information: the possible values of $\\pi$ and the relative prior plausibility of each.  \n\n2.Upon observing data $Y = y$, define the **likelihood function** $L(\\pi|y)$.    \n    As a first step, we summarize the dependence of $Y$ on $\\pi$ via a **conditional pmf** $f(y|\\pi)$.  The likelihood function is then defined by $L(\\pi|y) = f(y|\\pi)$ and can be used to compare the relative likelihood of different $\\pi$ values in light of data $Y = y$.\n\n\n## In Summary\n\n3.Build the **posterior model** of $\\pi$ via Bayes' Rule.    \n    By Bayes' Rule, the posterior model is constructed by balancing the prior and likelihood:\n\n$$\\text{posterior} = \\frac{\\text{prior} \\cdot \\text{likelihood}}{\\text{normalizing constant}} \\propto \\text{prior} \\cdot \\text{likelihood}$$\nMore technically,\n    \n$$f(\\pi|y) = \\frac{f(\\pi)L(\\pi|y)}{f(y)} \\propto f(\\pi)L(\\pi|y)$$\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}